In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches_test_week9.csv", index_col=0)

In [3]:
matches = matches.drop(columns=["opp formation"])

In [4]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
NaN,26/10/2024,16:00,Premier League,Matchweek 9,Sat,Home,NaN,NaN,NaN,Ipswich Town,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brentford
NaN,26/10/2024,16:00,Premier League,Matchweek 10,Sat,Home,NaN,NaN,NaN,Wolves,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brighton and Hove Albion
NaN,26/10/2024,16:00,Premier League,Matchweek 11,Sat,Home,NaN,NaN,NaN,Bournemouth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Aston Villa
NaN,26/10/2024,16:00,Premier League,Matchweek 12,Sat,Home,NaN,NaN,NaN,Southampton,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manchester City
NaN,26/10/2024,16:30,Premier League,Matchweek 13,Sat,Home,NaN,NaN,NaN,Fulham,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Everton

In [6]:
matches["team"].value_counts()

team
Brentford                   47
Brighton and Hove Albion    47
Aston Villa                 47
Manchester City             47
Everton                     47
Wolverhampton Wanderers     46
Crystal Palace              46
West Ham United             46
Manchester United           46
Bournemouth                 46
Fulham                      46
Newcastle United            46
Nottingham Forest           46
Tottenham Hotspur           46
Chelsea                     46
Arsenal                     46
Liverpool                   46
Luton Town                  38
Burnley                     38
Sheffield United            38
Leicester City               8
Ipswich Town                 8
Southampton                  8
Name: count, dtype: int64

In [7]:
matches[matches["team"] == "Liverpool"].sort_values("date")

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
28.0,01/01/2024,20:00,Premier League,Matchweek 20,Mon,Home,W,4.0,2.0,Newcastle Utd,...,Match Report,NaN,32.0,12.0,16.2,0.0,1.0,2.0,2023.0,Liverpool
2.0,01/09/2024,16:00,Premier League,Matchweek 3,Sun,Away,W,3.0,0.0,Manchester Utd,...,Match Report,NaN,11.0,3.0,13.4,0.0,0.0,0.0,2024.0,Liverpool
41.0,02/03/2024,15:00,Premier League,Matchweek 27,Sat,Away,W,1.0,0.0,Nott'ham Forest,...,Match Report,NaN,22.0,1.0,14.6,0.0,0.0,0.0,2023.0,Liverpool
3.0,03/09/2023,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,Match Report,NaN,17.0,4.0,14.7,0.0,0.0,0.0,2023.0,Liverpool
20.0,03/12/2023,14:00,Premier League,Matchweek 14,Sun,Home,W,4.0,3.0,Fulham,...,Match Report,NaN,26.0,12.0,18.9,1.0,0.0,0.0,2023.0,Liverpool
35.0,04/02/2024,16:30,Premier League,Matchweek 23,Sun,Away,L,1.0,3.0,Arsenal,...,Match Report,NaN,10.0,1.0,19.7,0.0,0.0,0.0,2023.0,Liverpool
47.0,04/04/2024,19:30,Premier League,Matchweek 31,Thu,Home,W,3.0,1.0,Sheffield Utd,...,Match Report,NaN,29.0,9.0,18.1,1.0,0.0,0.0,2023.0,Liverpool
55.0,05/05/2024,16:30,Premier League,Matchweek 36,Sun,Home,W,4.0,2.0,Tottenham,...,Match Report,NaN,25.0,12.0,15.3,0.0,0.0,0.0,2023.0,Liverpool
9.0,05/10/2024,12:30,Premier League,Matchweek 7,Sat,Away,W,1.0,0.0,Crystal Palace,...,Match Report,NaN,16.0,4.0,18.9,0.0,0.0,0.0,2024.0,Liverpool
15.0,05/11/2023,16:30,Premier League,Matchweek 11,Sun,Away,D,1.0,1.0,Luton Town,...,Match Report,NaN,24.0,6.0,17.5,0.0,0.0,0.0,2023.0,Liverpool
21.0,06/12/2023,19:30,Premier League,Matchweek 15,Wed,Away,W,2.0,0.0,Sheffield Utd,...,Match Report,NaN,15.0,8.0,16.4,0.0,0.0,0.0,2023.0,Liverpool
48.0,07/04/2024,15:30,Premier League,Matchweek 32,Sun,Away,D,2.0,2.0,Manchester Utd,...,Match Report,NaN,27.0,6.0,17.5,0.0,1.0,1.0,2023.0,Liverpool
10.0,08/10/2023,14:00,Premier League,Matchweek 8,Sun,Away,D,2.0,2.0,Brighton,...,Match Report,NaN,13.0,3.0,18.8,0.0,1.0,1.0,2023.0,Liverpool
22.0,09/12/2023,12:30,Premier League,Matchweek 16,Sat,Away,W,2.0,1.0,Crystal Palace,...,Match Report,NaN,14.0,2.0,17.4,0.0,0.0,0.0,2023.0,Liverpool
36.0,10/02/2024,15:00,Premier League,Matchweek 24,Sat,Home,W,3.0,1.0,Burnley,...,Match Report,NaN,25.0,10.0,15.4,0.0,0.0,0.0,2023.0,Liverpool
43.0,10/03/2024,15:45,Premier League,Matchweek 28,Sun,Home,D,1.0,1.0,Manchester City,...,Match Report,NaN,18.0,5.0,19.0,1.0,1.0,1.0,2023.0,Liverpool
17.0,12/11/2023,14:00,Premier League,Matchweek 12,Sun,Home,W,3.0,0.0,Brentford,...,Match Report,NaN,17.0,10.0,19.0,0.0,0.0,0.0,2023.0,Liverpool
56.0,13/05/2024,20:00,Premier League,Matchweek 37,Mon,Away,D,3.0,3.0,Aston Villa,...,Match Report,NaN,14.0,7.0,17.1,0.0,0.0,0.0,2023.0,Liverpool
0.0,13/08/2023,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,Match Report,NaN,13.0,1.0,17.8,0.0,0.0,0.0,2023.0,Liverpool
50.0,14/04/2024,14:00,Premier League,Matchweek 33,Sun,Home,L,0.0,1.0,Crystal Palace,...,Match Report,NaN,21.0,5.0,12.5,1.0,0.0,0.0,2023.0,Liverpool
3.0,14/09/2024,15:00,Premier League,Matchweek 4,Sat,Home,L,0.0,1.0,Nott'ham Forest,...,Match Report,NaN,14.0,5.0,14.9,0.0,0.0,0.0,2024.0,Liverpool
4.0,16/09/2023,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,Match Report,NaN,16.0,5.0,15.8,0.0,0.0,0.0,2023.0,Liverpool
37.0,17/02/2024,12:30,Premier League,Matchweek 25,Sat,Away,W,4.0,1.0,Brentford,...,Match Report,NaN,15.0,8.0,15.9,1.0,0.0,0.0,2023.0,Liverpool
0.0,17/08/2024,12:30,Premier League,Matchweek 1,Sat,Away,W,2.0,0.0,Ipswich Town,...,Match Report,NaN,18.0,5.0,14.8,0.0,0.0,0.0,2024.0,Liverpool
24.0,17/12/2023,16:30,Premier League,Matchweek 17,Sun,Home,D,0.0,0.0,Manchester Utd,...,Match Report,NaN,34.0,8.0,17.7,0.0,0.0,0.0,2023.0,Liverpool
57.0,19/05/2024,16:00,Premier League,Matchweek 38,Sun,Home,W,2.0,0.0,Wolves,...,Match Report,NaN,36.0,13.0,14.8,0.0,0.0,0.0,2023.0,Liverpool
1.0,19/08/2023,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,Match Report,NaN,25.0,9.0,16.8,1.0,0.0,1.0,2023.0,Liverpool
10.0,20/10/2024,16:30,Premier League,Matchweek 8,Sun,Home,W,2.0,1.0,Chelsea,...,Match Report,NaN,8.0,4.0,22.7,1.0,1.0,1.0,2024.0,Liverpool
31.0,21/01/2024,16:30,Premier League,Matchweek 21,Sun,Away,W,4.0,0.0,Bournemouth,...,Match Report,NaN,14.0,7.0,19.2,0.0,0.0,0.0,2023.0,Liverpool
38.0,21/02/2024,19:30,Premier League,Matchweek 26,Wed,Home,W,4.0,1.0,Luton Town,...,Match Report,NaN,29.0,13.0,16.9,0.0,0.0,0.0,2023.0,Liverpool
52.0,21/04/2024,16:30,Premier League,Matchweek 34,Sun,Away,W,3.0,1.0,Fulham,...,Match Report,NaN,14.0,7.0,18.8,2.0,0.0,0.0,2023.0,Liverpool
5.0,21/09/2024,15:00,Premier League,Matchweek 5,Sat,Home,W,3.0,0.0,Bournemouth,...,Match Report,NaN,19.0,12.0,16.6,0.0,0.0,0.0,2024.0,Liverpool
11.0,21/10/2023,12:30,Premier League,Matchweek 9,Sat,Home,W,2.0,0.0,Everton,...,Match Report,NaN,25.0,5.0,22.4,1.0,1.0,1.0,2023.0,Liverpool
26.0,23/12/2023,17:30,Premier League,Matchweek 18,Sat,Home,D,1.0,1.0,Arsenal,...,Match Report,NaN,13.0,3.0,20.1,1.0,0.0,0.0,2023.0,Liverpool
53.0,24/04/2024,20:00,Premier League,Matchweek 29,Wed,Away,L,0.0,2.0,Everton,...,Match Report,NaN,23.0,7.0,16.8,0.0,0.0,0.0,2023.0,Liverpool
6.0,24/09/2023,14:00,Premier League,Matchweek 6,Sun,Home,W,3.0,1.0,West Ham,...,Match Report,NaN,21.0,6.0,19.3,2.0,1.0,1.0,2023.0,Liverpool
1.0,25/08/2024,16:30,Premier League,Matchweek 2,Sun,Home,W,2.0,0.0,Brentford,...,Match Report,NaN,19.0,8.0,13.6,1.0,0.0,0.0,2024.0,Liverpool
18.0,25/11/2023,12:30,Premier League,Matchweek 13,Sat,Away,D,1.0,1.0,Manchester City,...,Match Report,NaN,8.0,3.0,15.9,0.0,0.0,0.0,2023.0,Liverpool
27.0,26/12/2023,17:30,Premier League,Matchweek 19,Tue,Away,W,2.0,0.0,Burnley,...,Match Report,NaN,19.0,10.0,17.4,0.0,0.0,0.0,2023.0,Liverpool
54.0,27/04/2024,12:30,Premier League,Matchweek 35,Sat,Away,D,2.0,2.0,West Ham,...,Match Report,NaN,28.0,8.0,16.6,1.0,0.0,0.0,2023.0,Liverpool
2.0,27/08/2023,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,Match Report,NaN,9.0,4.0,17.2,1.0,0.0,0.0,2023.0,Liverpool
7.0,28/09/2024,17:30,Premier League,Matchweek 6,Sat,Away,W,2.0,1.0,Wolves,...,Match Report,NaN,9.0,5.0,18.0,1.0,1.0,1.0,2024.0,Liverpool
13.0,29/10/2023,14:00,Premier League,Matchweek 10,Sun,Home,W,3.0,0.0,Nott'ham Forest,...,Match Report,NaN,21.0,8.0,19.5,2.0,0.0,0.0,2023.0,Liverpool
8.0,30/09/2023,17:30,Premier League,Matchweek 7,Sat,Away,L,1.0,2.0,Tottenham,...,Match Report,NaN,12.0,4.0,14.9,0.0,0.0,0.0,2023.0,Liverpool
34.0,31/01/2024,20:15,Premier League,Matchweek 22,Wed,Home,W,4.0,1.0,Chelsea,...,Match Report,NaN,27.0,13.0,19.9,2.0,0.0,1.0,2023.0,Liverpool
46.0,31/03/2024,14:00,Premier League,Matchweek 30,Sun,Home,W,2.0,1.0,Brighton,...,Match Report,NaN,30.0,8.0,16.6,0.0,0.0,0.0,2023.0,Liverpool

In [8]:
matches["round"].value_counts()

round
Matchweek 8     40
Matchweek 5     40
Matchweek 7     40
Matchweek 6     40
Matchweek 1     40
Matchweek 2     40
Matchweek 3     40
Matchweek 4     40
Matchweek 10    21
Matchweek 9     21
Matchweek 13    21
Matchweek 12    21
Matchweek 11    21
Matchweek 26    20
Matchweek 34    20
Matchweek 37    20
Matchweek 36    20
Matchweek 35    20
Matchweek 29    20
Matchweek 33    20
Matchweek 32    20
Matchweek 31    20
Matchweek 30    20
Matchweek 28    20
Matchweek 27    20
Matchweek 21    20
Matchweek 18    20
Matchweek 25    20
Matchweek 24    20
Matchweek 23    20
Matchweek 22    20
Matchweek 20    20
Matchweek 19    20
Matchweek 17    20
Matchweek 16    20
Matchweek 15    20
Matchweek 14    20
Matchweek 38    20
Name: count, dtype: int64

In [9]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season          float64
team             object
dtype: object

In [10]:
del matches["comp"]

In [11]:
del matches["notes"]

In [12]:
matches["date"] = pd.to_datetime(matches["date"])

C:\Users\edgar\AppData\Local\Temp\ipykernel_17700\2174778740.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  matches["date"] = pd.to_datetime(matches["date"])

In [13]:
matches["target"] = (matches["result"] == "W").astype("int")

In [14]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,match report,sh,sot,dist,fk,pk,pkatt,season,team,target
NaN,2024-10-26,16:00,Matchweek 9,Sat,Home,NaN,NaN,NaN,Ipswich Town,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brentford,0
NaN,2024-10-26,16:00,Matchweek 10,Sat,Home,NaN,NaN,NaN,Wolves,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brighton and Hove Albion,0
NaN,2024-10-26,16:00,Matchweek 11,Sat,Home,NaN,NaN,NaN,Bournemouth,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Aston Villa,0
NaN,2024-10-26,16:00,Matchweek 12,Sat,Home,NaN,NaN,NaN,Southampton,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manchester City,0
NaN,2024-10-26,16:30,Matchweek 13,Sat,Home,NaN,NaN,NaN,Fulham,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Everton,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36.0,2024-04-24,20:00,Matchweek 29,Wed,Away,L,2.0,4.0,Manchester Utd,0.8,...,Match Report,10.0,4.0,17.8,1.0,0.0,0.0,2023.0,Sheffield United,0
37.0,2024-04-27,15:00,Matchweek 35,Sat,Away,L,1.0,5.0,Newcastle Utd,1.5,...,Match Report,15.0,4.0,13.5,0.0,0.0,0.0,2023.0,Sheffield United,0
38.0,2024-05-04,15:00,Matchweek 36,Sat,Home,L,1.0,3.0,Nott'ham Forest,2.2,...,Match Report,16.0,4.0,18.0,0.0,1.0,1.0,2023.0,Sheffield United,0
39.0,2024-05-11,15:00,Matchweek 37,Sat,Away,L,0.0,1.0,Everton,0.6,...,Match Report,13.0,1.0,21.0,0.0,0.0,0.0,2023.0,Sheffield United,0
40.0,2024-05-19,16:00,Matchweek 38,Sun,Home,L,0.0,3.0,Tottenham,1.0,...,Match Report,6.0,1.0,18.0,1.0,0.0,0.0,2023.0,Sheffield United,0

In [15]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [16]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [17]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [18]:
matches["day_code"] = matches["date"].dt.dayofweek

In [19]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
NaN,2024-10-26,16:00,Matchweek 9,Sat,Home,NaN,NaN,NaN,Ipswich Town,NaN,...,NaN,NaN,NaN,NaN,Brentford,0,1,10,16,5
NaN,2024-10-26,16:00,Matchweek 10,Sat,Home,NaN,NaN,NaN,Wolves,NaN,...,NaN,NaN,NaN,NaN,Brighton and Hove Albion,0,1,22,16,5
NaN,2024-10-26,16:00,Matchweek 11,Sat,Home,NaN,NaN,NaN,Bournemouth,NaN,...,NaN,NaN,NaN,NaN,Aston Villa,0,1,2,16,5
NaN,2024-10-26,16:00,Matchweek 12,Sat,Home,NaN,NaN,NaN,Southampton,NaN,...,NaN,NaN,NaN,NaN,Manchester City,0,1,19,16,5
NaN,2024-10-26,16:30,Matchweek 13,Sat,Home,NaN,NaN,NaN,Fulham,NaN,...,NaN,NaN,NaN,NaN,Everton,0,1,9,16,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36.0,2024-04-24,20:00,Matchweek 29,Wed,Away,L,2.0,4.0,Manchester Utd,0.8,...,1.0,0.0,0.0,2023.0,Sheffield United,0,0,15,20,2
37.0,2024-04-27,15:00,Matchweek 35,Sat,Away,L,1.0,5.0,Newcastle Utd,1.5,...,0.0,0.0,0.0,2023.0,Sheffield United,0,0,16,15,5
38.0,2024-05-04,15:00,Matchweek 36,Sat,Home,L,1.0,3.0,Nott'ham Forest,2.2,...,0.0,1.0,1.0,2023.0,Sheffield United,0,1,17,15,5
39.0,2024-05-11,15:00,Matchweek 37,Sat,Away,L,0.0,1.0,Everton,0.6,...,0.0,0.0,0.0,2023.0,Sheffield United,0,0,8,15,5
40.0,2024-05-19,16:00,Matchweek 38,Sun,Home,L,0.0,3.0,Tottenham,1.0,...,1.0,0.0,0.0,2023.0,Sheffield United,0,1,20,16,6

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [22]:
train = matches[matches["date"] < '2024-10-25']

In [23]:
test = matches[matches["date"] > '2024-10-25']

In [24]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [25]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [26]:
preds = rf.predict(test[predictors])

In [27]:
preds

array([0, 1, 1, 1, 0])

In [36]:
# Obtén las probabilidades para cada clase
probabilidades = rf.predict_proba(test[predictors])
# Convierte a DataFrame para una visualización más fácil
df_resultados = pd.DataFrame(probabilidades, columns=rf.classes_)
df_resultados['Predicción'] = rf.predict(test[predictors])

print(df_resultados)

          0         1  Predicción
0  0.607731  0.392269           0
1  0.364519  0.635481           1
2  0.466004  0.533996           1
3  0.127359  0.872641           1
4  0.760116  0.239884           0

In [35]:
test

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
NaN,2024-10-26,16:00,Matchweek 9,Sat,Home,NaN,NaN,NaN,Ipswich Town,NaN,...,NaN,NaN,NaN,NaN,Brentford,0,1,10,16,5
NaN,2024-10-26,16:00,Matchweek 10,Sat,Home,NaN,NaN,NaN,Wolves,NaN,...,NaN,NaN,NaN,NaN,Brighton and Hove Albion,0,1,22,16,5
NaN,2024-10-26,16:00,Matchweek 11,Sat,Home,NaN,NaN,NaN,Bournemouth,NaN,...,NaN,NaN,NaN,NaN,Aston Villa,0,1,2,16,5
NaN,2024-10-26,16:00,Matchweek 12,Sat,Home,NaN,NaN,NaN,Southampton,NaN,...,NaN,NaN,NaN,NaN,Manchester City,0,1,19,16,5
NaN,2024-10-26,16:30,Matchweek 13,Sat,Home,NaN,NaN,NaN,Fulham,NaN,...,NaN,NaN,NaN,NaN,Everton,0,1,9,16,5

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
error = accuracy_score(test["target"], preds)

In [30]:
error

0.4

In [31]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [32]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted  0  1
actual
0          2  3

In [33]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)

0.0

In [35]:
grouped_matches = matches.groupby("team")

In [36]:
group = grouped_matches.get_group("Manchester City").sort_values("date")

In [37]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [38]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
5,2023-09-02,15:00,Matchweek 4,Sat,Home,W,5.0,1.0,Fulham,2.2,...,15,5,2.000000,0.333333,20.000000,7.000000,16.366667,0.666667,0.000000,0.333333
6,2023-09-16,15:00,Matchweek 5,Sat,Away,W,3.0,1.0,West Ham,3.6,...,15,5,2.666667,0.666667,16.333333,5.666667,16.666667,0.666667,0.333333,0.666667
8,2023-09-23,15:00,Matchweek 6,Sat,Home,W,2.0,0.0,Nott'ham Forest,1.3,...,15,5,3.333333,1.000000,21.333333,8.666667,16.166667,1.000000,0.333333,0.666667
10,2023-09-30,15:00,Matchweek 7,Sat,Away,L,1.0,2.0,Wolves,0.9,...,15,5,3.333333,0.666667,14.000000,7.000000,16.133333,1.000000,0.333333,0.333333
12,2023-10-08,16:30,Matchweek 8,Sun,Away,L,0.0,1.0,Arsenal,0.5,...,16,6,2.000000,1.000000,19.666667,8.333333,17.633333,1.333333,0.000000,0.000000
13,2023-10-21,15:00,Matchweek 9,Sat,Home,W,2.0,1.0,Brighton,0.8,...,15,5,1.000000,1.000000,11.333333,4.000000,17.133333,1.000000,0.000000,0.000000
15,2023-10-29,15:30,Matchweek 10,Sun,Away,W,3.0,0.0,Manchester Utd,4.0,...,15,6,1.000000,1.333333,12.333333,4.333333,17.666667,0.666667,0.000000,0.000000
16,2023-11-04,15:00,Matchweek 11,Sat,Home,W,6.0,1.0,Bournemouth,1.9,...,15,5,1.666667,0.666667,11.333333,4.666667,16.966667,1.000000,0.333333,0.333333
18,2023-11-12,16:30,Matchweek 12,Sun,Away,D,4.0,4.0,Chelsea,2.9,...,16,6,3.666667,0.666667,17.000000,7.333333,17.466667,1.000000,0.333333,0.333333
19,2023-11-25,12:30,Matchweek 13,Sat,Home,D,1.0,1.0,Liverpool,1.3,...,12,5,4.333333,1.666667,18.333333,8.666667,16.733333,1.000000,0.666667,0.666667
21,2023-12-03,16:30,Matchweek 14,Sun,Home,D,3.0,3.0,Tottenham,2.6,...,16,6,3.666667,2.000000,17.000000,7.333333,16.433333,0.666667,0.333333,0.333333
22,2023-12-06,20:15,Matchweek 15,Wed,Away,L,0.0,1.0,Aston Villa,0.6,...,20,2,2.666667,2.666667,15.666667,6.000000,15.433333,0.666667,0.333333,0.333333
23,2023-12-10,14:00,Matchweek 16,Sun,Away,W,2.0,1.0,Luton Town,1.6,...,14,6,1.333333,1.666667,11.666667,3.666667,12.366667,0.333333,0.000000,0.000000
25,2023-12-16,15:00,Matchweek 17,Sat,Home,D,2.0,2.0,Crystal Palace,1.6,...,15,5,1.666667,1.666667,12.333333,4.000000,13.166667,0.333333,0.000000,0.000000
26,2023-12-27,20:15,Matchweek 19,Wed,Away,W,3.0,1.0,Everton,2.4,...,20,2,1.333333,1.333333,13.000000,5.666667,14.766667,0.333333,0.000000,0.000000
27,2023-12-30,15:00,Matchweek 20,Sat,Home,W,2.0,0.0,Sheffield Utd,2.2,...,15,5,2.333333,1.333333,19.666667,7.666667,18.800000,0.666667,0.333333,0.333333
29,2024-01-13,17:30,Matchweek 21,Sat,Away,W,3.0,2.0,Newcastle Utd,3.0,...,17,5,2.333333,1.000000,19.666667,7.000000,18.366667,0.333333,0.333333,0.333333
31,2024-01-31,19:30,Matchweek 22,Wed,Home,W,3.0,1.0,Burnley,1.7,...,19,2,2.666667,1.000000,22.333333,7.666667,18.733333,1.000000,0.333333,0.333333
32,2024-02-05,20:00,Matchweek 23,Mon,Away,W,3.0,1.0,Brentford,2.1,...,20,0,2.666667,1.000000,19.666667,6.333333,17.500000,1.000000,0.000000,0.000000
33,2024-02-10,12:30,Matchweek 24,Sat,Home,W,2.0,0.0,Everton,1.6,...,12,5,3.000000,1.333333,22.000000,10.000000,18.100000,1.000000,0.000000,0.000000
35,2024-02-17,17:30,Matchweek 25,Sat,Home,D,1.0,1.0,Chelsea,2.6,...,17,5,2.666667,0.666667,19.333333,7.333333,17.466667,0.333333,0.000000,0.000000
36,2024-02-20,19:30,Matchweek 18,Tue,Home,W,1.0,0.0,Brentford,2.3,...,19,1,2.000000,0.666667,25.000000,7.666667,17.500000,0.333333,0.000000,0.000000
37,2024-02-24,17:30,Matchweek 26,Sat,Away,W,1.0,0.0,Bournemouth,1.6,...,17,5,1.333333,0.333333,25.000000,6.000000,16.966667,0.333333,0.000000,0.000000
39,2024-03-03,15:30,Matchweek 27,Sun,Home,W,3.0,1.0,Manchester Utd,3.3,...,15,6,1.000000,0.333333,23.666667,7.000000,16.333333,0.666667,0.000000,0.000000
41,2024-03-10,15:45,Matchweek 28,Sun,Away,D,1.0,1.0,Liverpool,1.6,...,15,6,1.666667,0.333333,22.333333,8.000000,16.933333,0.666667,0.000000,0.000000
43,2024-03-31,16:30,Matchweek 30,Sun,Home,D,0.0,0.0,Arsenal,1.0,...,16,6,1.666667,0.666667,17.333333,6.666667,17.266667,0.666667,0.000000,0.000000
44,2024-04-03,20:15,Matchweek 31,Wed,Home,W,4.0,1.0,Aston Villa,3.4,...,20,2,1.333333,0.666667,16.333333,5.000000,16.833333,0.333333,0.000000,0.000000
45,2024-04-06,12:30,Matchweek 32,Sat,Away,W,4.0,2.0,Crystal Palace,1.9,...,12,5,1.666667,0.666667,15.666667,6.000000,16.233333,0.666667,0.000000,0.000000
47,2024-04-13,15:00,Matchweek 33,Sat,Home,W,5.0,1.0,Luton Town,4.2,...,15,5,2.666667,1.000000,18.333333,6.666667,15.400000,0.666667,0.000000,0.000000
50,2024-04-25,20:00,Matchweek 29,Thu,Away,W,4.0,0.0,Brighton,1.4,...,20,3,4.333333,1.333333,26.333333,10.333333,16.300000,0.666667,0.333333,0.333333
51,2024-04-28,16:30,Matchweek 35,Sun,Away,W,2.0,0.0,Nott'ham Forest,0.9,...,16,6,4.333333,1.000000,22.666667,8.666667,16.666667,0.333333,0.333333,0.333333
52,2024-05-04,17:30,Matchweek 36,Sat,Home,W,5.0,1.0,Wolves,3.7,...,17,5,3.666667,0.333333,20.333333,7.666667,17.533333,0.666667,0.333333,0.333333
53,2024-05-11,12:30,Matchweek 37,Sat,Away,W,4.0,0.0,Fulham,3.2,...,12,5,3.666667,0.333333,14.333333,7.000000,17.000000,0.666667,0.666667,0.666667
54,2024-05-14,20:00,Matchweek 34,Tue,Away,W,2.0,0.0,Tottenham,2.4,...,20,1,3.666667,0.333333,14.666667,7.666667,17.200000,0.333333,1.000000,1.000000
55,2024-05-19,16:00,Matchweek 38,Sun,Home,W,3.0,1.0,West Ham,1.9,...,16,6,3.666667,0.333333,13.333333,7.333333,15.800000,0.000000,1.333333,1.333333
1,2024-08-18,16:30,Matchweek 1,Sun,Away,W,2.0,0.0,Chelsea,0.8,...,16,6,3.000000,0.333333,16.666667,8.000000,16.666667,0.666667,0.666667,0.666667
2,2024-08-24,15:00,Matchweek 2,Sat,Home,W,4.0,1.0,Ipswich Town,3.3,...,15,5,2.333333,0.333333,15.333333,7.000000,17.166667,0.666667,0.333333,0.333333
3,2024-08-31,17:30,Matchweek 3,Sat,Away,W,3.0,1.0,West Ham,3.0,...,17,5,3.000000,0.666667,17.333333,7.000000,18.266667,1.000000,0.333333,0.333333
4,2024-09-14,15:00,Matchweek 4,Sat,Home,W,2.0,1.0,Brentford,2.1,...,15,5,3.000000,0.666667,15.666667,5.666667,17.300000,0.666667,0.333333,0.333333
6,2024-09-22,16:30,Matchweek 5,Sun,Home,D,2.0,2.0,Arsenal,2.1,...,16,6,3.000000,1.000000,18.000000,6.333333,16.666667,0.666667,0.333333,0.333333
8,2024-09-28,12:30,Matchweek 6,Sat,Away,D,1.0,1.0,Newcastle Utd,0.9,...,12,5,2.333333,1.333333,24.666667,8.666667,17.466667,0.666667,0.000000,0.000000
10,2024-10-05,15:00,Matchweek 7,Sat,Home,W,3.0,2.0,Fulham,1.6,...,15,5,1.666667,1.333333,22.333333,8.000000,18.333333,0.333333,0.000000,0.000000
11,2024-10-20,14:00,Matchweek 8,Sun,Away,W,2.0,1.0,Wolves,1.6,...,14,6,2.000000,1.666667,23.000000,8.000000,18.466667,0.666667,0.000000,0.000000

In [39]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

C:\Users\edgar\AppData\Local\Temp\ipykernel_23744\4052147919.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [40]:
matches_rolling

                                 date   time        round  day venue result  \
team
Arsenal                 4  2023-09-03  16:30  Matchweek 4  Sun  Home      W
                        5  2023-09-17  16:30  Matchweek 5  Sun  Away      W
                        7  2023-09-24  14:00  Matchweek 6  Sun  Home      D
                        9  2023-09-30  15:00  Matchweek 7  Sat  Away      W
                        11 2023-10-08  16:30  Matchweek 8  Sun  Home      W
...                               ...    ...          ...  ...   ...    ...
Wolverhampton Wanderers 4  2024-09-15  16:30  Matchweek 4  Sun  Home      L
                        6  2024-09-21  15:00  Matchweek 5  Sat  Away      L
                        7  2024-09-28  17:30  Matchweek 6  Sat  Home      L
                        8  2024-10-05  15:00  Matchweek 7  Sat  Away      L
                        9  2024-10-20  14:00  Matchweek 8  Sun  Home      L

                             gf   ga         opponent   xg  ...  hour  \
team                                                        ...
Arsenal                 4   3.0  1.0   Manchester Utd  2.3  ...    16
                        5   1.0  0.0          Everton  1.0  ...    16
                        7   2.0  2.0        Tottenham  1.8  ...    14
                        9   4.0  0.0      Bournemouth  3.4  ...    15
                        11  1.0  0.0  Manchester City  0.4  ...    16
...                         ...  ...              ...  ...  ...   ...
Wolverhampton Wanderers 4   1.0  2.0    Newcastle Utd  1.2  ...    16
                        6   1.0  3.0      Aston Villa  0.5  ...    15
                        7   1.0  2.0        Liverpool  0.6  ...    17
                        8   3.0  5.0        Brentford  1.0  ...    15
                        9   1.0  2.0  Manchester City  0.8  ...    14

                            day_code  gf_rolling ga_rolling sh_rolling  \
team
Arsenal                 4          6    1.666667   1.000000  15.333333
                        5          6    2.000000   1.000000  16.000000
                        7          6    2.000000   1.000000  16.000000
                        9          5    2.000000   1.000000  14.000000
                        11         6    2.333333   0.666667  12.666667
...                              ...         ...        ...        ...
Wolverhampton Wanderers 4          6    1.000000   3.000000  10.666667
                        6          5    1.333333   3.000000  11.666667
                        7          5    1.000000   2.000000  11.000000
                        8          5    1.000000   2.333333  10.000000
                        9          6    1.666667   3.333333  11.666667

                           sot_rolling dist_rolling  fk_rolling  pk_rolling  \
team
Arsenal                 4     6.000000    16.433333    0.000000    0.666667
                        5     5.333333    15.066667    0.000000    0.666667
                        7     6.000000    15.400000    0.000000    0.333333
                        9     4.333333    16.433333    0.000000    0.333333
                        11    4.666667    16.600000    0.000000    1.000000
...                                ...          ...         ...         ...
Wolverhampton Wanderers 4     3.000000    19.700000    0.666667    0.000000
                        6     3.666667    18.333333    0.333333    0.000000
                        7     3.666667    16.933333    0.000000    0.000000
                        8     4.000000    17.666667    0.000000    0.000000
                        9     4.333333    19.566667    0.000000    0.000000

                            pkatt_rolling
team
Arsenal                 4        0.666667
                        5        0.666667
                        7        0.333333
                        9        0.333333
                        11       1.000000
...                                   ...
Wolverhampton Wanderers 4        0.000000
                        6        0.000000
                        7        0.000000
                        8        0.000000
                        9        0.000000

[851 rows x 38 columns]

In [41]:
matches_rolling = matches_rolling.droplevel('team')

In [42]:
matches_rolling.to_csv("matchesvisualizar.csv")

In [43]:
matches_rolling.index = range(matches_rolling.shape[0])

In [44]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [45]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

ValueError: Found array with 0 sample(s) (shape=(0, 12)) while a minimum of 1 is required by RandomForestClassifier.

In [ ]:
error

In [ ]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [ ]:
combined.head(10)

In [ ]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [ ]:
combined["new_team"] = combined["team"].map(mapping)

In [ ]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [ ]:
merged

In [ ]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()